#java
# Use the official OpenJDK image as a base
FROM openjdk:11

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the project files into the container
COPY . .

# Compile and run the Java application
#CMD ["javac", "Main.java"]
CMD ["java", "Main"]